In [1]:
import pandas as pd
from utilities.preprocessors import preprocess, assign_gender, series_to_1D_array, construct_embedding_dict, construct_embedding_matrix
from utilities.visualizers import view_rows
from utilities.loaders import load_file
from models.fil_lstm_glove import load_lstm_model

import os
from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

# Load dataframe

In [2]:
conn_info = pd.read_csv('../documents/conn_info.csv', index_col=0)
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,transcosmos Asia Philippines Inc. · Full-time,https://www.linkedin.com/in/jamie-rose-cleofas...,Jamie Rose Cleofas,NaN,NaN
1066,jovitfrias@gmail.com,0,RCM Health Care Services · Full-time,https://www.linkedin.com/in/jovit-frias-06a561...,Jovit Frias,NaN,NaN
1067,danlopezatwork@gmail.com,0,Abacus Service Corporation · Full-time,https://www.linkedin.com/in/danlopezprofessional/,Mark Daniel Lopez,NaN,NaN
1068,dmrc_06@yahoo.com,09983696222 (Mobile),RingCentral · Full-time,https://www.linkedin.com/in/daena-michaela-roy...,Daena Michaela Ceria,NaN,NaN


In [3]:
conn_info['gender'].unique()

array(['male', 'female', nan], dtype=object)

In [4]:
# what I want to do is if there are names that have more than 1 first name e.g.
# Jherick and Sid, we want to train a classifier that classifies these individual
# names and output its probability and then average these two probabilities to get
# the final probability of whether it is male or female name
# i.e. Jherick has prob 0.75732 of being positive label Sid has prob of 0.6343 of
# being a positive label the average of this would be 0.69581 which would be a postive
# label, wee can assign the positive label 1 to a male label and the negative label 0
# would be female
conn_info['conn_name'].apply(lambda name: name.split() if not pd.isna(name) else name)

0                    [Marcus, Paulino]
1            [Jherick, Sid, Celestial]
2       [Evan, Jake, Soriano, Montano]
3                   [Reggielee, Capio]
4                 [John, Carlo, Tadeo]
                     ...              
1065            [Jamie, Rose, Cleofas]
1066                    [Jovit, Frias]
1067             [Mark, Daniel, Lopez]
1068          [Daena, Michaela, Ceria]
1069              [Joana, Mace, Reyes]
Name: conn_name, Length: 1070, dtype: object

# Loading libraries for gender classifier

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import one_hot

# Loading dataset for gender classifier

In [6]:
name_gender_df = pd.read_csv('./data/name_gender_dataset.csv')
name_gender_df

,Name,Gender,Count,Probability
0,James,M,5304407,1.451679e-02
1,John,M,5260831,1.439753e-02
2,Robert,M,4970386,1.360266e-02
3,Michael,M,4579950,1.253414e-02
4,William,M,4226608,1.156713e-02
...,...,...,...,...
147264,Zylenn,M,1,2.736740e-09
147265,Zymeon,M,1,2.736740e-09
147266,Zyndel,M,1,2.736740e-09
147267,Zyshan,M,1,2.736740e-09


In [7]:
name_gender_df['Gender'].value_counts()

Gender
F    89749
M    57520
Name: count, dtype: int64

#### 0 for male 1 for female

In [8]:
name_gender_df['Gender'] = name_gender_df['Gender'].apply(lambda label: 0 if label == 'M' else 1)
name_gender_df['Gender'].value_counts()

Gender
1    89749
0    57520
Name: count, dtype: int64

In [9]:
# split into training and testing
X_trains, X_tests, Y_trains, Y_tests = train_test_split(name_gender_df['Name'], name_gender_df['Gender'], test_size=0.2, random_state=0)
X_trains

2853        Kamden
143300       Qiang
111302    Evthokia
27499       Tasean
84175     Elysiana
            ...   
41993       Adryel
97639       Caydan
95939     Sturgill
117952     Breonny
43567       Kinjal
Name: Name, Length: 117815, dtype: object

#### dataset indicates a slight imbalance therefore it may be useful to use AUC and F1 as a metric rather than accuracy 

In [10]:
# what we should do is encode each name we have into a numerical value
unique_train_names = X_trains.unique().tolist()
unique_train_names

['Kamden',
 'Qiang',
 'Evthokia',
 'Tasean',
 'Elysiana',
 'Vermon',
 'Zaylem',
 'Kuiam',
 'Konesha',
 'Jayga',
 'Ark',
 'Evelin',
 'Termaine',
 'Debraca',
 'Georgiane',
 'Rebbekah',
 'Martene',
 'Dianni',
 'Lyric',
 'Panithi',
 'Joanny',
 'Ivory',
 'Brindle',
 'Akai',
 'Koa',
 'Yosniel',
 'Huldah',
 'Ireri',
 'Amanoa',
 'Tsung-Wei',
 'Tosca',
 'Zander',
 'Didier',
 'Shacara',
 'Mariah-Lee',
 'Amiella',
 'Khushpreet',
 'Shauna-Ann',
 'Babram',
 'Kornell',
 'Catessa',
 'Izah',
 'Treisha',
 'Kidae',
 'Corlis',
 'Alana-Jade',
 'Edsil',
 'Arleyah',
 'Boe',
 'Sehreen',
 'Hareshwar',
 'Josiahh',
 'Liberti',
 'Devahn',
 'Lyra',
 'Sirach',
 'Maki',
 'Danieljames',
 'Maezy',
 'Rea',
 'Michaile',
 'Guinette',
 'Ezequias',
 'Creztinez',
 'Khrystina',
 'Bhagwana',
 'Kanyon',
 'Nicharon',
 'Deamontae',
 'Zeilah',
 'Hemi-Alex',
 'Skyelar',
 'Rorik',
 'Mave',
 'Niya',
 'Rawen',
 'Popi',
 'Toya',
 'Azeeza',
 'Uniquia',
 'Trager',
 'Emin',
 'Amarah',
 'Maomi',
 'Jemeria',
 'Shanrell',
 'Anjani',
 'Jaha

In [11]:
# what we should do is encode each name we have into a numerical value
unique_test_names = X_tests.unique().tolist()
unique_test_names

['Hans-Christian',
 'Dilhan',
 'Zohar',
 'Myrl',
 'Broadie',
 'Sitta',
 'Duyen',
 'Nesaru',
 'Xeormenas',
 'Bauer',
 'Xamiyah',
 'Euella',
 'Racheale',
 'Yazmyn',
 'Yamille',
 'Lillie',
 'Siyuri',
 'Wylee',
 'Larod',
 'Ashalee',
 'Amaryah',
 'Doyla',
 'Kearstyn',
 'Esprit',
 'Heber',
 'Aszure',
 'Tyki',
 'Summerlynn',
 'Versal',
 'Seiko',
 'Shawntai',
 'Rehaazvir',
 'Carlson',
 'Loreita',
 'Noriah',
 'Sienna-Jai',
 'Shelvrene',
 'Ganajah',
 'Xaida',
 'Reather',
 'Myrella',
 'Krsevan',
 'Demorea',
 'Crisslyn',
 'Michilu',
 'Syliss',
 'Keisha',
 'Gino-Carlo',
 'Billijean',
 'Chalonda',
 'Shakeeka',
 'Kola',
 'Arthalia',
 'Eraclis',
 'Leinaala',
 'Lynley',
 'Addylin',
 'Cerinity',
 'Tassie',
 'Bersain',
 'Julysa',
 'Kaillou',
 'Paolo-Nino',
 'Shawntasia',
 'Adam',
 'Guisepina',
 'Merrick',
 'Margena',
 'Buck',
 'Karmandeep',
 'Aliyyah',
 'Aisha',
 'Gemma',
 'Taviana',
 'Katherine',
 'Reynna',
 'Talyssa',
 'Hakar',
 'Constant',
 'Vice',
 'Chadsten',
 'Demi-Rose',
 'Czeslow',
 'Staffon',
 '

In [12]:
# before joining again get array in df with longest length first
name_with_max = max(unique_train_names, key=lambda name: len(name.split('-')))
train_max_len = len(name_with_max.split('-'))
train_max_len

4

In [13]:
num_unique_train_names = len(unique_train_names)
num_unique_train_names

109292

In [14]:
num_unique_test_names = len(unique_test_names)
num_unique_test_names

28939

In [15]:
X_trains

2853        Kamden
143300       Qiang
111302    Evthokia
27499       Tasean
84175     Elysiana
            ...   
41993       Adryel
97639       Caydan
95939     Sturgill
117952     Breonny
43567       Kinjal
Name: Name, Length: 117815, dtype: object

In [16]:
# omit split argument since the string column of the df is not a sentence 
# and is just a one word string which is a name
tokenizer = Tokenizer(num_words=num_unique_train_names, split=" ")
tokenizer.fit_on_texts(X_trains)

In [17]:
word_to_index = tokenizer.word_index
index_to_word = tokenizer.index_word

In [18]:
index_to_word

{1: 'lee',
 2: 'anne',
 3: 'rose',
 4: 'ann',
 5: 'marie',
 6: 'jane',
 7: 'louise',
 8: 'jade',
 9: 'maria',
 10: 'may',
 11: 'jo',
 12: 'james',
 13: 'john',
 14: 'leigh',
 15: 'anna',
 16: 'lea',
 17: 'jayne',
 18: 'mae',
 19: 'jean',
 20: 'grace',
 21: 'jay',
 22: 'kate',
 23: 'mary',
 24: 'maree',
 25: 'paul',
 26: 'joy',
 27: 'rae',
 28: 'sue',
 29: 'minh',
 30: 'lyn',
 31: 'emma',
 32: 'michelle',
 33: 'lily',
 34: 'skye',
 35: 'lisa',
 36: 'anthony',
 37: 'jae',
 38: 'kim',
 39: 'ella',
 40: 'amy',
 41: 'michael',
 42: 'smt',
 43: 'an',
 44: 'peter',
 45: 'thanh',
 46: 'anh',
 47: 'mark',
 48: 'angela',
 49: 'ruby',
 50: 'lynn',
 51: 'sarah',
 52: 'mia',
 53: 'jai',
 54: 'jayde',
 55: 'mai',
 56: 'elizabeth',
 57: 'renee',
 58: 'daniel',
 59: 'luke',
 60: 'leah',
 61: 'nicole',
 62: 'thuy',
 63: 'jaye',
 64: 'amanda',
 65: 'emily',
 66: 'ngoc',
 67: 'ellen',
 68: 'kelly',
 69: 'paige',
 70: 'andrew',
 71: 'laura',
 72: 'claire',
 73: 'hoang',
 74: 'dee',
 75: 'david',
 76: 'sha

In [19]:
word_to_index

{'lee': 1,
 'anne': 2,
 'rose': 3,
 'ann': 4,
 'marie': 5,
 'jane': 6,
 'louise': 7,
 'jade': 8,
 'maria': 9,
 'may': 10,
 'jo': 11,
 'james': 12,
 'john': 13,
 'leigh': 14,
 'anna': 15,
 'lea': 16,
 'jayne': 17,
 'mae': 18,
 'jean': 19,
 'grace': 20,
 'jay': 21,
 'kate': 22,
 'mary': 23,
 'maree': 24,
 'paul': 25,
 'joy': 26,
 'rae': 27,
 'sue': 28,
 'minh': 29,
 'lyn': 30,
 'emma': 31,
 'michelle': 32,
 'lily': 33,
 'skye': 34,
 'lisa': 35,
 'anthony': 36,
 'jae': 37,
 'kim': 38,
 'ella': 39,
 'amy': 40,
 'michael': 41,
 'smt': 42,
 'an': 43,
 'peter': 44,
 'thanh': 45,
 'anh': 46,
 'mark': 47,
 'angela': 48,
 'ruby': 49,
 'lynn': 50,
 'sarah': 51,
 'mia': 52,
 'jai': 53,
 'jayde': 54,
 'mai': 55,
 'elizabeth': 56,
 'renee': 57,
 'daniel': 58,
 'luke': 59,
 'leah': 60,
 'nicole': 61,
 'thuy': 62,
 'jaye': 63,
 'amanda': 64,
 'emily': 65,
 'ngoc': 66,
 'ellen': 67,
 'kelly': 68,
 'paige': 69,
 'andrew': 70,
 'laura': 71,
 'claire': 72,
 'hoang': 73,
 'dee': 74,
 'david': 75,
 'shae': 

In [20]:
word_to_index["kamden"]

1865

In [21]:
index_to_word[1865]

'kamden'

In [22]:
train_seqs = tokenizer.texts_to_sequences(X_trains)
train_seqs[:10]

[[1865],
 [10249],
 [10250],
 [1866],
 [10251],
 [10252],
 [10253],
 [10254],
 [10255],
 [10256]]

In [23]:
test_seqs = tokenizer.texts_to_sequences(X_tests)
test_seqs[:10]

[[417, 548], [], [18700], [], [58156], [], [], [], [], []]

In [24]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
train_seqs_padded = pad_sequences(train_seqs, maxlen=train_max_len, padding='post', truncating='post')
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

In [25]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
test_seqs_padded = pad_sequences(test_seqs, maxlen=train_max_len, padding='post', truncating='post')
test_seqs_padded

array([[  417,   548,     0,     0],
       [    0,     0,     0,     0],
       [18700,     0,     0,     0],
       ...,
       [    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int32)

In [26]:
Y_trains

2853      0
143300    0
111302    1
27499     0
84175     1
         ..
41993     0
97639     1
95939     0
117952    1
43567     1
Name: Gender, Length: 117815, dtype: int64

In [27]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
train_unique_labels = Y_trains.unique()
len_train_unique_labels = len(train_unique_labels)
len_train_unique_labels
# train_Y_oh = one_hot(Y_trains, depth=len_train_unique_labels).numpy()
# train_Y_oh

2

In [28]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
test_unique_labels = Y_tests.unique()
len_test_unique_labels = len(test_unique_labels)
len_test_unique_labels
# test_Y_oh = one_hot(Y_tests, depth=len_test_unique_labels).numpy()
# test_Y_oh

2

In [36]:
test_unique_labels

array([0, 1])

In [99]:
# includes oov words
vocab_len = len(word_to_index) + 1
# emb_dict, emb_vec_len = construct_embedding_dict('./embeddings/glove.twitter.27B.50d.txt', word_to_index)
# emb_matrix = construct_embedding_matrix(word_to_index, emb_dict, emb_vec_len)
lstm_model = load_lstm_model(train_max_len, vocab_len)

input shape: 4


In [100]:
# emb_matrix.shape

In [101]:
# emb_matrix.any(axis=1).sum()

In [102]:
lstm_model.summary()

Model: "fil-name-gender-lstm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding-layer (Embedding)     │ (None, 4, 256)         │    26,679,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_20                │ (None, 256)            │       394,240 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │           257 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_20 (Activation)      │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 27,074,305 (103.28 MB)

 Trainable params: 27,074,305 (103.28 MB)

 Non-trainable params: 0 (0.00 B)

In [103]:
lstm_model.get_layer('embedding-layer').trainable

True

In [104]:
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

https://www.kaggle.com/code/shrikrishnaparab/gender-prediction-based-on-name-using-lstm

In [106]:
lstm_history = lstm_model.fit(
    train_seqs_padded, Y_trains,
    batch_size=64,
    epochs=10,
    validation_split=0.2,
)

Epoch 1/10
 110/1473 ━━━━━━━━━━━━━━━━━━━━ 2:45 121ms/step - auc_9: 0.5000 - binary_accuracy: 0.6077 - binary_crossentropy: 9.7545 - f1_score: 0.7560 - loss: 0.2464 - precision_9: 0.6077 - recall_9: 1.0000

KeyboardInterrupt: 

In [ ]:
lstm_history