In [207]:
import pandas as pd
import numpy as np

from utilities.preprocessors import preprocess, assign_gender, series_to_1D_array, map_value_to_index
from utilities.visualizers import view_rows
from utilities.loaders import load_file
from models.fil_lstm_glove import load_lstm_model

import os
import re

from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Load dataframe

In [208]:
conn_info = pd.read_csv('../documents/conn_info.csv', index_col=0)
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,transcosmos Asia Philippines Inc. · Full-time,https://www.linkedin.com/in/jamie-rose-cleofas...,Jamie Rose Cleofas,NaN,NaN
1066,jovitfrias@gmail.com,0,RCM Health Care Services · Full-time,https://www.linkedin.com/in/jovit-frias-06a561...,Jovit Frias,NaN,NaN
1067,danlopezatwork@gmail.com,0,Abacus Service Corporation · Full-time,https://www.linkedin.com/in/danlopezprofessional/,Mark Daniel Lopez,NaN,NaN
1068,dmrc_06@yahoo.com,09983696222 (Mobile),RingCentral · Full-time,https://www.linkedin.com/in/daena-michaela-roy...,Daena Michaela Ceria,NaN,NaN


In [209]:
conn_info['gender'].unique()

array(['male', 'female', nan], dtype=object)

In [210]:
# what I want to do is if there are names that have more than 1 first name e.g.
# Jherick and Sid, we want to train a classifier that classifies these individual
# names and output its probability and then average these two probabilities to get
# the final probability of whether it is male or female name
# i.e. Jherick has prob 0.75732 of being positive label Sid has prob of 0.6343 of
# being a positive label the average of this would be 0.69581 which would be a postive
# label, wee can assign the positive label 1 to a male label and the negative label 0
# would be female
conn_info['conn_name'].apply(lambda name: name.split() if not pd.isna(name) else name)

0                    [Marcus, Paulino]
1            [Jherick, Sid, Celestial]
2       [Evan, Jake, Soriano, Montano]
3                   [Reggielee, Capio]
4                 [John, Carlo, Tadeo]
                     ...              
1065            [Jamie, Rose, Cleofas]
1066                    [Jovit, Frias]
1067             [Mark, Daniel, Lopez]
1068          [Daena, Michaela, Ceria]
1069              [Joana, Mace, Reyes]
Name: conn_name, Length: 1070, dtype: object

# Loading libraries for gender classifier

In [211]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import one_hot

# Loading dataset for gender classifier

In [212]:
name_gender_df = pd.read_csv('./data/name_gender_dataset.csv')
name_gender_df

,Name,Gender,Count,Probability
0,James,M,5304407,1.451679e-02
1,John,M,5260831,1.439753e-02
2,Robert,M,4970386,1.360266e-02
3,Michael,M,4579950,1.253414e-02
4,William,M,4226608,1.156713e-02
...,...,...,...,...
147264,Zylenn,M,1,2.736740e-09
147265,Zymeon,M,1,2.736740e-09
147266,Zyndel,M,1,2.736740e-09
147267,Zyshan,M,1,2.736740e-09


In [213]:
name_gender_df['Gender'].value_counts()

Gender
F    89749
M    57520
Name: count, dtype: int64

#### 0 for male 1 for female

In [214]:
name_gender_df['Gender'] = name_gender_df['Gender'].apply(lambda label: 0 if label == 'M' else 1)
name_gender_df['Gender'].value_counts()

Gender
1    89749
0    57520
Name: count, dtype: int64

In [215]:
name_gender_df["Name"] = name_gender_df["Name"].apply(lambda name: name.lower())
name_gender_df

,Name,Gender,Count,Probability
0,james,0,5304407,1.451679e-02
1,john,0,5260831,1.439753e-02
2,robert,0,4970386,1.360266e-02
3,michael,0,4579950,1.253414e-02
4,william,0,4226608,1.156713e-02
...,...,...,...,...
147264,zylenn,0,1,2.736740e-09
147265,zymeon,0,1,2.736740e-09
147266,zyndel,0,1,2.736740e-09
147267,zyshan,0,1,2.736740e-09


In [216]:
def helper(row):
    # splits the name into smaller chunks if the name
    # is more than 1
    
    name = row["Name"]
    gender = row["Gender"]

    new_name = re.sub(r'[^0-9A-Za-z]', " ", name)
    split_name = new_name.split(' ')
    if len(split_name) > 1:
        return [(name_chunk, gender) for name_chunk in split_name]
    
    return [(name, gender)]

In [217]:
name_gender_exp = name_gender_df.apply(helper, axis=1).to_list()
name_gender_exp

[[('james', 0)],
 [('john', 0)],
 [('robert', 0)],
 [('michael', 0)],
 [('william', 0)],
 [('mary', 1)],
 [('david', 0)],
 [('joseph', 0)],
 [('richard', 0)],
 [('charles', 0)],
 [('thomas', 0)],
 [('christopher', 0)],
 [('daniel', 0)],
 [('matthew', 0)],
 [('elizabeth', 1)],
 [('patricia', 1)],
 [('jennifer', 1)],
 [('anthony', 0)],
 [('george', 0)],
 [('linda', 1)],
 [('barbara', 1)],
 [('donald', 0)],
 [('paul', 0)],
 [('mark', 0)],
 [('andrew', 0)],
 [('steven', 0)],
 [('kenneth', 0)],
 [('edward', 0)],
 [('joshua', 0)],
 [('margaret', 1)],
 [('brian', 0)],
 [('kevin', 0)],
 [('jessica', 1)],
 [('sarah', 1)],
 [('susan', 1)],
 [('timothy', 0)],
 [('dorothy', 1)],
 [('jason', 0)],
 [('ronald', 0)],
 [('helen', 1)],
 [('ryan', 0)],
 [('jeffrey', 0)],
 [('karen', 1)],
 [('nancy', 1)],
 [('betty', 1)],
 [('lisa', 1)],
 [('jacob', 0)],
 [('nicholas', 0)],
 [('ashley', 1)],
 [('eric', 0)],
 [('frank', 0)],
 [('gary', 0)],
 [('anna', 1)],
 [('stephen', 0)],
 [('jonathan', 0)],
 [('sandra'

In [218]:
name_gender_exp_flat = series_to_1D_array(name_gender_exp)
name_gender_exp_flat

[('james', 0),
 ('john', 0),
 ('robert', 0),
 ('michael', 0),
 ('william', 0),
 ('mary', 1),
 ('david', 0),
 ('joseph', 0),
 ('richard', 0),
 ('charles', 0),
 ('thomas', 0),
 ('christopher', 0),
 ('daniel', 0),
 ('matthew', 0),
 ('elizabeth', 1),
 ('patricia', 1),
 ('jennifer', 1),
 ('anthony', 0),
 ('george', 0),
 ('linda', 1),
 ('barbara', 1),
 ('donald', 0),
 ('paul', 0),
 ('mark', 0),
 ('andrew', 0),
 ('steven', 0),
 ('kenneth', 0),
 ('edward', 0),
 ('joshua', 0),
 ('margaret', 1),
 ('brian', 0),
 ('kevin', 0),
 ('jessica', 1),
 ('sarah', 1),
 ('susan', 1),
 ('timothy', 0),
 ('dorothy', 1),
 ('jason', 0),
 ('ronald', 0),
 ('helen', 1),
 ('ryan', 0),
 ('jeffrey', 0),
 ('karen', 1),
 ('nancy', 1),
 ('betty', 1),
 ('lisa', 1),
 ('jacob', 0),
 ('nicholas', 0),
 ('ashley', 1),
 ('eric', 0),
 ('frank', 0),
 ('gary', 0),
 ('anna', 1),
 ('stephen', 0),
 ('jonathan', 0),
 ('sandra', 1),
 ('emily', 1),
 ('amanda', 1),
 ('kimberly', 1),
 ('michelle', 1),
 ('donna', 1),
 ('justin', 0),
 ('laur

#### Checking if there are still rows/names with '-' char

In [219]:
list(filter(lambda row: '-' in row[0], name_gender_exp))[:20]

[]

#### checking if there are still items in the `name_gender_exp_flat` that are lists

In [220]:
list(filter(lambda item: len(item) > 1, name_gender_exp))[:20]

[[('jo', 1), ('anne', 1)],
 [('jo', 1), ('ann', 1)],
 [('anne', 1), ('marie', 1)],
 [('zo', 1), ('', 1)],
 [('lee', 1), ('anne', 1)],
 [('lee', 1), ('ann', 1)],
 [('smt', 1), ('', 1)],
 [('ann', 1), ('marie', 1)],
 [('chlo', 1), ('', 1)],
 [('julie', 1), ('anne', 1)],
 [('mary', 1), ('ann', 1)],
 [('julie', 1), ('ann', 1)],
 [('am', 1), ('lie', 1)],
 [('lori', 1), ('ann', 1)],
 [('d', 0), ('arcy', 0)],
 [('mary', 1), ('anne', 1)],
 [('ma', 1), ('lle', 1)],
 [('emma', 1), ('lee', 1)],
 [('sarah', 1), ('jane', 1)],
 [('anna', 1), ('marie', 1)]]

In [221]:
list(filter(lambda item: type(item) == list, name_gender_exp_flat))[:20]

[]

In [222]:
name_gender_exp_flat

[('james', 0),
 ('john', 0),
 ('robert', 0),
 ('michael', 0),
 ('william', 0),
 ('mary', 1),
 ('david', 0),
 ('joseph', 0),
 ('richard', 0),
 ('charles', 0),
 ('thomas', 0),
 ('christopher', 0),
 ('daniel', 0),
 ('matthew', 0),
 ('elizabeth', 1),
 ('patricia', 1),
 ('jennifer', 1),
 ('anthony', 0),
 ('george', 0),
 ('linda', 1),
 ('barbara', 1),
 ('donald', 0),
 ('paul', 0),
 ('mark', 0),
 ('andrew', 0),
 ('steven', 0),
 ('kenneth', 0),
 ('edward', 0),
 ('joshua', 0),
 ('margaret', 1),
 ('brian', 0),
 ('kevin', 0),
 ('jessica', 1),
 ('sarah', 1),
 ('susan', 1),
 ('timothy', 0),
 ('dorothy', 1),
 ('jason', 0),
 ('ronald', 0),
 ('helen', 1),
 ('ryan', 0),
 ('jeffrey', 0),
 ('karen', 1),
 ('nancy', 1),
 ('betty', 1),
 ('lisa', 1),
 ('jacob', 0),
 ('nicholas', 0),
 ('ashley', 1),
 ('eric', 0),
 ('frank', 0),
 ('gary', 0),
 ('anna', 1),
 ('stephen', 0),
 ('jonathan', 0),
 ('sandra', 1),
 ('emily', 1),
 ('amanda', 1),
 ('kimberly', 1),
 ('michelle', 1),
 ('donna', 1),
 ('justin', 0),
 ('laur

In [223]:
names, genders = list(zip(*name_gender_exp_flat))
names

('james',
 'john',
 'robert',
 'michael',
 'william',
 'mary',
 'david',
 'joseph',
 'richard',
 'charles',
 'thomas',
 'christopher',
 'daniel',
 'matthew',
 'elizabeth',
 'patricia',
 'jennifer',
 'anthony',
 'george',
 'linda',
 'barbara',
 'donald',
 'paul',
 'mark',
 'andrew',
 'steven',
 'kenneth',
 'edward',
 'joshua',
 'margaret',
 'brian',
 'kevin',
 'jessica',
 'sarah',
 'susan',
 'timothy',
 'dorothy',
 'jason',
 'ronald',
 'helen',
 'ryan',
 'jeffrey',
 'karen',
 'nancy',
 'betty',
 'lisa',
 'jacob',
 'nicholas',
 'ashley',
 'eric',
 'frank',
 'gary',
 'anna',
 'stephen',
 'jonathan',
 'sandra',
 'emily',
 'amanda',
 'kimberly',
 'michelle',
 'donna',
 'justin',
 'laura',
 'ruth',
 'carol',
 'brandon',
 'larry',
 'scott',
 'melissa',
 'stephanie',
 'benjamin',
 'raymond',
 'samuel',
 'rebecca',
 'deborah',
 'gregory',
 'sharon',
 'kathleen',
 'amy',
 'cynthia',
 'alexander',
 'patrick',
 'jack',
 'henry',
 'angela',
 'shirley',
 'emma',
 'catherine',
 'katherine',
 'virgini

In [224]:
new_name_gender_df = pd.DataFrame({'name': names, 'gender': genders})
new_name_gender_df

,name,gender
0,james,0
1,john,0
2,robert,0
3,michael,0
4,william,0
...,...,...
155125,zylenn,0
155126,zymeon,0
155127,zyndel,0
155128,zyshan,0


In [242]:
# split into training and testing
trains, tests = train_test_split(new_name_gender_df, test_size=0.2, random_state=0)
trains

,name,gender
58421,enrike,0
44132,karo,0
6768,donna,0
104257,taimani,1
38115,abrial,1
...,...,...
97639,braizlee,1
95939,quali,0
152315,shivji,0
117952,amy,1


#### dataset indicates a slight imbalance therefore it may be useful to use AUC and F1 as a metric rather than accuracy 

In [244]:
# what we should do is encode each name we have into a numerical value
unique_train_names = trains['name'].unique().tolist()
unique_train_names

['enrike',
 'karo',
 'donna',
 'taimani',
 'abrial',
 'etrulia',
 'mandria',
 'aciel',
 'nhial',
 'lavie',
 'shawnae',
 'pramil',
 'shaquon',
 'aitlin',
 'editha',
 'siohban',
 'atyanna',
 'izidor',
 'rossieanna',
 'sherwyn',
 'tays',
 'sienne',
 'radvin',
 'klea',
 'genene',
 'aarish',
 'tyia',
 'dyneshia',
 'imoghen',
 'briellen',
 'shaney',
 'nikylja',
 'jayne',
 'kathy',
 'taitoko',
 'tyler',
 'meera',
 'crystalmarie',
 'quilla',
 'azrya',
 'olisia',
 'aubriona',
 'cranstone',
 'atilla',
 'neddy',
 'attis',
 'reegen',
 'aleeka',
 'conya',
 'emir',
 'tana',
 'kashmir',
 'ayasha',
 'dejene',
 'brianna',
 'shakida',
 'marie',
 'jhared',
 'jaiquez',
 'saelah',
 'dao',
 'gillard',
 'ammaar',
 'leonor',
 'evelynrose',
 'garnet',
 'jeffrey',
 'herodotus',
 'markya',
 'henrick',
 'iniyan',
 'greysyn',
 'naufahu',
 'arliene',
 'deryon',
 'vear',
 'trella',
 'milei',
 'jamine',
 'majok',
 'wilmar',
 'heysam',
 'antares',
 'lourena',
 'odell',
 'glentyn',
 'musfirah',
 'neiva',
 'loreley',
 '

In [245]:
# what we should do is encode each name we have into a numerical value
unique_test_names = tests['name'].unique().tolist()
unique_test_names

['monique',
 'brishae',
 'jaimison',
 'labasse',
 'neilina',
 'linda',
 'fakir',
 'syriah',
 'leigh',
 'samela',
 'jatziry',
 'kirstie',
 'teeya',
 'waverly',
 'kedrian',
 'haq',
 'comekia',
 'juanne',
 'juniel',
 'deshna',
 'dilynn',
 'harce',
 'jurij',
 'allan',
 'kahle',
 'azemara',
 'brasia',
 'navi',
 'tobey',
 'weslie',
 'mandi',
 'dataar',
 'sherrica',
 'ayudia',
 'dimitris',
 'pasqualine',
 'malika',
 'mary',
 'luie',
 'sanaii',
 'phillipos',
 'cynai',
 'caileen',
 'tracy',
 'jenniya',
 'seta',
 'jakailyn',
 'elverta',
 'may',
 'jaecyon',
 'jackaline',
 'tamina',
 'bernadeth',
 'antigone',
 'caua',
 'rhodney',
 'grosvenor',
 'keili',
 'ayoob',
 'mesut',
 'mckeyla',
 'kiera',
 'trome',
 'brienne',
 'jabree',
 'charndy',
 'ellisen',
 'jeromey',
 'annesha',
 'analysse',
 'kiaash',
 'maria',
 'nishanth',
 'khusbhoo',
 'amandarose',
 'amanie',
 'dejanai',
 'carya',
 'khalial',
 'aelianna',
 'basra',
 'armetha',
 'tennell',
 'leara',
 'johnbenedict',
 'neana',
 'hansraj',
 'jamaria',

In [246]:
# before joining again get array in df with longest length first
name_with_max = max(unique_train_names, key=len)
name_with_max

'polyentolyekmongtainh'

In [247]:
train_max_len = len(name_with_max)
train_max_len

21

In [248]:
num_unique_train_names = len(unique_train_names)
num_unique_train_names

104133

In [249]:
num_unique_test_names = len(unique_test_names)
num_unique_test_names

28467

In [250]:
X_trains

,name,gender
58421,enrike,0
44132,karo,0
6768,donna,0
104257,taimani,1
38115,abrial,1
...,...,...
97639,braizlee,1
95939,quali,0
152315,shivji,0
117952,amy,1


In [251]:
chars, counts = np.unique(series_to_1D_array(trains['name']), return_counts=True)
chars

array(['0', '8', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',
       'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x',
       'y', 'z'], dtype='<U1')

In [252]:
counts

array([     5,      1, 132036,  10235,  16158,  23618,  86492,   4017,
         8368,  34523,  67789,  13292,  18557,  50257,  24788,  70348,
        31672,   5332,   2100,  52198,  36766,  29576,  16261,   9096,
         4236,   1587,  29658,   6837])

#### mapping each character to their respective indeces

In [253]:
char_to_idx = map_value_to_index(chars)
idx_to_char = map_value_to_index(chars, inverted=True)


In [254]:
char_to_idx('a')

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [255]:
char_to_idx('b')

<tf.Tensor: shape=(), dtype=int64, numpy=4>

#### Unknown or 'UNK' characters are mapped to 0


In [256]:
char_to_idx('#')

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
trains['name'].apply(lambda name: [char_to_idx(char) for char in name])


In [24]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
train_seqs_padded = pad_sequences(train_seqs, maxlen=train_max_len, padding='post', truncating='post')
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

In [25]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
test_seqs_padded = pad_sequences(test_seqs, maxlen=train_max_len, padding='post', truncating='post')
test_seqs_padded

array([[  417,   548,     0,     0],
       [    0,     0,     0,     0],
       [18700,     0,     0,     0],
       ...,
       [    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int32)

In [26]:
Y_trains

2853      0
143300    0
111302    1
27499     0
84175     1
         ..
41993     0
97639     1
95939     0
117952    1
43567     1
Name: Gender, Length: 117815, dtype: int64

In [27]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
train_unique_labels = Y_trains.unique()
len_train_unique_labels = len(train_unique_labels)
len_train_unique_labels
# train_Y_oh = one_hot(Y_trains, depth=len_train_unique_labels).numpy()
# train_Y_oh

2

In [28]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
test_unique_labels = Y_tests.unique()
len_test_unique_labels = len(test_unique_labels)
len_test_unique_labels
# test_Y_oh = one_hot(Y_tests, depth=len_test_unique_labels).numpy()
# test_Y_oh

2

In [36]:
test_unique_labels

array([0, 1])

In [99]:
# includes oov words
vocab_len = len(word_to_index) + 1
# emb_dict, emb_vec_len = construct_embedding_dict('./embeddings/glove.twitter.27B.50d.txt', word_to_index)
# emb_matrix = construct_embedding_matrix(word_to_index, emb_dict, emb_vec_len)
lstm_model = load_lstm_model(train_max_len, vocab_len)

input shape: 4


In [100]:
# emb_matrix.shape

In [101]:
# emb_matrix.any(axis=1).sum()

In [102]:
lstm_model.summary()

Model: "fil-name-gender-lstm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding-layer (Embedding)     │ (None, 4, 256)         │    26,679,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_20                │ (None, 256)            │       394,240 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │           257 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_20 (Activation)      │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 27,074,305 (103.28 MB)

 Trainable params: 27,074,305 (103.28 MB)

 Non-trainable params: 0 (0.00 B)

In [103]:
lstm_model.get_layer('embedding-layer').trainable

True

In [104]:
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

https://www.kaggle.com/code/shrikrishnaparab/gender-prediction-based-on-name-using-lstm

In [106]:
lstm_history = lstm_model.fit(
    train_seqs_padded, Y_trains,
    batch_size=64,
    epochs=10,
    validation_split=0.2,
)

Epoch 1/10
 110/1473 ━━━━━━━━━━━━━━━━━━━━ 2:45 121ms/step - auc_9: 0.5000 - binary_accuracy: 0.6077 - binary_crossentropy: 9.7545 - f1_score: 0.7560 - loss: 0.2464 - precision_9: 0.6077 - recall_9: 1.0000

KeyboardInterrupt: 

In [ ]:
lstm_history